CREATE TABLE MEDICATION(
	REGISTRO INT PRIMARY KEY NOT NULL,
	PRODUTO VARCHAR(200),
	PRINCIPIO_ATIVO VARCHAR(200),
	LABORATORIO VARCHAR(200),
	CLASSE_TERAPEUTICA VARCHAR(200),
	APRESENTACAO VARCHAR(300),
	TARJA VARCHAR(60),
	COMERCIALIZACAO_2022 VARCHAR(5)
);