CREATE TABLE  IF NOT EXISTS MEDICATION(
	REGISTRO BIGINT NOT NULL,
	PRODUTO VARCHAR(300),
	PRINCIPIO_ATIVO VARCHAR(2000),
	LABORATORIO VARCHAR(300),
	CLASSE_TERAPEUTICA VARCHAR(500),
	APRESENTACAO VARCHAR(300),
	TARJA VARCHAR(60),
	COMERCIALIZACAO_2022 VARCHAR(5)
);